import type {
  DaneAdresatow,
  DaneDokumentacjiMaterialow,
  DaneFormularza,
  GrupaSzkoleniowa,
} from './typy'

export const poczatkowaDokumentacja: DaneDokumentacjiMaterialow = {
  listaObecnosci: true,
  ankiety: true,
  certyfikaty: true,
  program: true,
  kartaInformacyjna: true,
  materialyInspekcyjne: false,
  podreczniki: false,
  materialyDodatkowe: false,
  testPrzedPo: false,
  dostepnoscCyfrowa: false,
  kompletDlaZamawiajacego: false,
  wzorKlienta: false,
  sposobDokumentu: 'druk',
  uwagi: '',
}

export const poczatkoweDaneFormularza: DaneFormularza = {
  tytulSzkolenia: '',
  organizator: 'SEMPER',
  status: 'NIEPEŁNE',
  nabywca: {
    nazwa: '',
    nip: '',
    adres: '',
  },
  odbiorca: {
    nazwa: '',
    nip: '',
    adres: '',
  },
  czyNabywcaJestOdbiorca: true,
  adresPaczkiWspolny: '',
  faktura: {
    sposob: '',
    email: '',
    uwagi: '',
  },
  raport: '',
  protokol: '',
  dataUmowy: '',
  numerUmowy: '',
  terminPlatnosci: '',
  kontaktWspolnyDlaGrup: true,
  koordynatorKlienta: {
    imieNazwisko: '',
    email: '',
    telefon: '',
  },
  odbiorcaPaczki: {
    imieNazwisko: '',
    email: '',
    telefon: '',
  },
  czyKoordynatorOdbieraPaczki: true,
  dokumentacja: { ...poczatkowaDokumentacja },
  materialy: '',
  logotypy: {
    czyWymagane: false,
    nazwaPliku: '',
    link: '',
    podglad: '',
    informacjaOFinansowaniu: '',
    zastrzezenie: '',
  },
  dodatkoweWymogi: {
    wczesniejszyPrzyjazdTrenera: false,
    minutyWczesniej: 0,
    dokumentacjaZdjęciowa: false,
    karyZaNieterminowosc: false,
    noweSzkolenieZaOcene: false,
    kfs: false,
    uwagi: '',
  },
  programSzkolenia: '',
  uwagi: {
    wewnetrzne: '',
    informacjeNiepewne: '',
    opiekuna: '',
    dlaKlienta: '',
    dlaTrenera: '',
    dlaWysylaczy: '',
  },
}

export const poczatkowaGrupa: GrupaSzkoleniowa = {
  id: 'grupa-1',
  nazwa: 'Grupa 1',
  statusTerminu: 'Niepotwierdzony',
  dataOd: '',
  dataDo: '',
  godzinaRozpoczecia: '',
  godzinaZakonczenia: '',
  formaSzkolenia: 'Stacjonarne',
  cenaNetto: 0,
  vat: '23%',
  cenaBrutto: 0,
  trybCeny: 'za grupę',
  liczbaGodzin: 0,
  rodzajGodzin: 'dydaktyczne',
  niestandardowaFormulaGodzin: '',
  lokalizacjaId: '',
  miejscownik: '',
  miejscownikPotwierdzony: false,
  miejsce: '',
  ktoZapewniaSale: '',
  nazwaLokalizacji: '',
  adresLokalizacji: '',
  sala: '',
  informacjeDojazdowe: '',
  platformaOnline: 'Zoom',
  linkOnline: '',
  kodDostepuOnline: '',
  informacjeTechniczne: '',
  trenerzy: [],
  czyTrenerSzkoliKazdaGrupe: false,
  dokumentacja: { ...poczatkowaDokumentacja },
  uczestnicy: [],
  liczbaUczestnikow: 0,
  pustaListaObecnosci: false,
  marginesWierszyListy: 8,
  koordynatorKlienta: {
    imieNazwisko: '',
    email: '',
    telefon: '',
  },
  odbiorcaPaczki: {
    imieNazwisko: '',
    email: '',
    telefon: '',
  },
}

export const poczatkowiAdresaci: DaneAdresatow = {
  reczniAdresaci: '',
  wyszukiwarka: '',
  wybraneGrupy: ['dzial-zamkniety'],
  trybTresci: 'cała treść',
  czyPodswietlacZmiany: true,
}

export function utworzPoczatkowaGrupe(indeks: number): GrupaSzkoleniowa {
  return {
    ...poczatkowaGrupa,
    id: `grupa-${Date.now()}-${indeks}`,
    nazwa: `Grupa ${indeks}`,
    dokumentacja: { ...poczatkowaDokumentacja },
    trenerzy: [],
    uczestnicy: [],
  }
}
