import type { TrenerKartoteki } from './typy'

type DaneTreneraCsv = {
  imie: string
  nazwisko: string
}

const trenerzyZCsv: DaneTreneraCsv[] = [
  { imie: 'Beata', nazwisko: 'Łapkowska' },
  { imie: 'Marzena', nazwisko: 'Badura' },
  { imie: 'Dariusz', nazwisko: 'Badura' },
  { imie: 'Jakub', nazwisko: 'Banaszewski' },
  { imie: 'Jakub', nazwisko: 'Bancerz' },
  { imie: 'Jan', nazwisko: 'Bańkowski' },
  { imie: 'Robert', nazwisko: 'Bartkowski' },
  { imie: 'Grzegorz', nazwisko: 'Basiński' },
  { imie: 'Adam', nazwisko: 'Baśkiewicz' },
  { imie: 'Magdalena', nazwisko: 'Błaszyk' },
  { imie: 'Agnieszka', nazwisko: 'Bednarczyk-Płachta' },
  { imie: 'Krzysztof', nazwisko: 'Betker' },
  { imie: 'Dobrawa', nazwisko: 'Biadun' },
  { imie: 'Daniel', nazwisko: 'Biegalski' },
  { imie: 'Kamil', nazwisko: 'Bieńkowski' },
  { imie: 'Andrzej', nazwisko: 'Bigaj' },
  { imie: 'Klaudia', nazwisko: 'Blachnicka' },
  { imie: 'Marcin', nazwisko: 'Bodziony' },
  { imie: 'Karolina', nazwisko: 'Bogumił-Łagowska' },
  { imie: 'Anita', nazwisko: 'Bogusch' },
  { imie: 'Agnieszka', nazwisko: 'Borkowska' },
  { imie: 'Mateusz', nazwisko: 'Borowiak' },
  { imie: 'Radosław', nazwisko: 'Bożek' },
  { imie: 'Rafał', nazwisko: 'Brodowski' },
  { imie: 'Ewa', nazwisko: 'Brzoza' },
  { imie: 'Kacper', nazwisko: 'Burczyk' },
  { imie: 'Iwona', nazwisko: 'Burka' },
  { imie: 'Izabela', nazwisko: 'Buszewicz' },
  { imie: 'Dawid', nazwisko: 'Chaba' },
  { imie: 'Monika', nazwisko: 'Chajec' },
  { imie: 'Krzysztof', nazwisko: 'Chudoń' },
  { imie: 'Patryk', nazwisko: 'Ciok' },
  { imie: 'Anna', nazwisko: 'Ciura-Sierota' },
  { imie: 'Alicja', nazwisko: 'Cugier' },
  { imie: 'Kamil', nazwisko: 'Czajkowski' },
  { imie: 'Marta', nazwisko: 'Czypicka' },
  { imie: 'Maciej', nazwisko: 'Dąbrowski' },
  { imie: 'Anna', nazwisko: 'Daszczyńska-Ciborowska' },
  { imie: 'Zygmunt', nazwisko: 'Dolata' },
  { imie: 'Szymon', nazwisko: 'Domek' },
  { imie: 'Kamila', nazwisko: 'Drelich' },
  { imie: 'Michał', nazwisko: 'Dróżdż' },
  { imie: 'Marcin', nazwisko: 'Drzazga' },
  { imie: 'Wojciech', nazwisko: 'Drzewiński' },
  { imie: 'Paula', nazwisko: 'Drzymała' },
  { imie: 'Grzegorz', nazwisko: 'Dudczak' },
  { imie: 'Beata', nazwisko: 'Dudkiewicz' },
  { imie: 'Kamil', nazwisko: 'Dybiec' },
  { imie: 'Marta', nazwisko: 'Dyda' },
  { imie: 'Natalia', nazwisko: 'Figiel' },
  { imie: 'Krzysztof', nazwisko: 'Fitrzyk' },
  { imie: 'Artur', nazwisko: 'Fojt' },
  { imie: 'Kamil', nazwisko: 'Gago' },
  { imie: 'Barbara', nazwisko: 'Głód' },
  { imie: 'Mariusz', nazwisko: 'Godlewski' },
  { imie: 'Adam', nazwisko: 'Górecki' },
  { imie: 'Joanna', nazwisko: 'Grabowska' },
  { imie: 'Krzysztof', nazwisko: 'Grodecki' },
  { imie: 'Marcin', nazwisko: 'Gronowski' },
  { imie: 'Dawid', nazwisko: 'Gruszka' },
  { imie: 'Przemysław', nazwisko: 'Grzegorczyk' },
  { imie: 'Wioleta', nazwisko: 'Grzybowska' },
  { imie: 'Anna', nazwisko: 'Gudowska' },
  { imie: 'Anna', nazwisko: 'Głusiec' },
  { imie: 'Rafał', nazwisko: 'Guzowski' },
  { imie: 'Tomasz', nazwisko: 'Gzela' },
  { imie: 'Aleksandra', nazwisko: 'Hadzik' },
  { imie: 'Paweł', nazwisko: 'Hermanowicz' },
  { imie: 'Estera', nazwisko: 'Hetmaniok-Kowalik' },
  { imie: 'Anna', nazwisko: 'Jabłecka' },
  { imie: 'Michał', nazwisko: 'Jagodziński' },
  { imie: 'Miłosz', nazwisko: 'Jan Łaski' },
  { imie: 'Ewa', nazwisko: 'Janas' },
  { imie: 'Jędrzej', nazwisko: 'Janiszewski' },
  { imie: 'Piotr', nazwisko: 'Jankowski' },
  { imie: 'Łukasz', nazwisko: 'Jaroszewski' },
  { imie: 'Adam', nazwisko: 'Jędrzejewski' },
  { imie: 'Marta', nazwisko: 'Józefiak' },
  { imie: 'Balbina', nazwisko: 'Kacprzyk' },
  { imie: 'Krzysztof', nazwisko: 'Kaczorowski' },
  { imie: 'Piotr', nazwisko: 'Kaleta' },
  { imie: 'Jeremiasz', nazwisko: 'Kalus' },
  { imie: 'Katarzyna', nazwisko: 'Kamecka' },
  { imie: 'Jolanta', nazwisko: 'Kamińska-Borak' },
  { imie: 'Maciej', nazwisko: 'Kamiński' },
  { imie: 'Marcin', nazwisko: 'Kałuża' },
  { imie: 'Mariusz', nazwisko: 'Kędzierski' },
  { imie: 'Maurycy', nazwisko: 'Kieruj' },
  { imie: 'Kamil', nazwisko: 'Kinas' },
  { imie: 'Katarzyna', nazwisko: 'Klemba' },
  { imie: 'Katarzyna', nazwisko: 'Klimowicz' },
  { imie: 'Grzegorz', nazwisko: 'Klonowski' },
  { imie: 'Maciej', nazwisko: 'Knap' },
  { imie: 'Monika', nazwisko: 'Kokosińska' },
  { imie: 'Agnieszka', nazwisko: 'Kolbuch-Węgiel' },
  { imie: 'Joanna', nazwisko: 'Kominiak' },
  { imie: 'Monika', nazwisko: 'Konopka' },
  { imie: 'Krzysztof', nazwisko: 'Konopka' },
  { imie: 'Rafał', nazwisko: 'Kołodziejczyk' },
  { imie: 'Sabina', nazwisko: 'Kościsz' },
  { imie: 'Paulina', nazwisko: 'Kosmowska' },
  { imie: 'Jakub', nazwisko: 'Kosowski' },
  { imie: 'Dominika', nazwisko: 'Kowalewicz' },
  { imie: 'Tomasz', nazwisko: 'Kowalewski' },
  { imie: 'Łukasz', nazwisko: 'Kowalski' },
  { imie: 'Kamil', nazwisko: 'Kowalski' },
  { imie: 'Tomasz', nazwisko: 'Kozłowski' },
  { imie: 'Mateusz', nazwisko: 'Kozłowski' },
  { imie: 'Michał', nazwisko: 'Krasiński' },
  { imie: 'Patrycja', nazwisko: 'Król-Tronina' },
  { imie: 'Piotr', nazwisko: 'Królewski' },
  { imie: 'Janusz', nazwisko: 'Kropornicki' },
  { imie: 'Grzegorz', nazwisko: 'Kryjom' },
  { imie: 'kpt.', nazwisko: 'Krzysztof Sługocki' },
  { imie: 'Patrycja', nazwisko: 'Kuba' },
  { imie: 'Kinga', nazwisko: 'Kuberek' },
  { imie: 'Marcin', nazwisko: 'Kucharek' },
  { imie: 'Anna', nazwisko: 'Kujaszewska' },
  { imie: 'Łukasz', nazwisko: 'Kukorowski' },
  { imie: 'Romana', nazwisko: 'Kukurba' },
  { imie: 'Paweł', nazwisko: 'Kurdziałek' },
  { imie: 'Sylwia', nazwisko: 'Kurdziel-Pajor' },
  { imie: 'Katarzyna', nazwisko: 'Kuśmierz' },
  { imie: 'Arkadiusz', nazwisko: 'Kuśpit' },
  { imie: 'Agata', nazwisko: 'Kwaśny' },
  { imie: 'Natalia', nazwisko: 'Lampkowska' },
  { imie: 'Marta', nazwisko: 'Lang' },
  { imie: 'Magdalena', nazwisko: 'Laskowska' },
  { imie: 'Dariusz', nazwisko: 'Leśniewski' },
  { imie: 'Grzegorz', nazwisko: 'Lewandowski' },
  { imie: 'Anna', nazwisko: 'Ligęza-Łaciok' },
  { imie: 'Aleksandra', nazwisko: 'Lindner' },
  { imie: 'Joanna', nazwisko: 'Lipińska' },
  { imie: 'Kamil', nazwisko: 'Lorek' },
  { imie: 'Dominik', nazwisko: 'Lorenc' },
  { imie: 'Edyta', nazwisko: 'Lorenc-Trąba' },
  { imie: 'Łukasz', nazwisko: 'Ludwina' },
  { imie: 'Bogusław', nazwisko: 'Machowski' },
  { imie: 'Paulina', nazwisko: 'Maciboch' },
  { imie: 'Bartosz', nazwisko: 'Magnowski' },
  { imie: 'hab.', nazwisko: 'Małgorzata Sieradzka' },
  { imie: 'Agnieszka', nazwisko: 'Marciniak' },
  { imie: 'Emilia', nazwisko: 'Marcinkowska' },
  { imie: 'Teresa', nazwisko: 'Maria Bleczyc' },
  { imie: 'Katarzyna', nazwisko: 'Maria Zawadzka' },
  { imie: 'Grzegorz', nazwisko: 'Markowski' },
  { imie: 'Tomasz', nazwisko: 'Marzec' },
  { imie: 'Sabrina', nazwisko: 'Maszkowska' },
  { imie: 'Maciej', nazwisko: 'Matys' },
  { imie: 'Agnieszka', nazwisko: 'Mazurek' },
  { imie: 'Bartosz', nazwisko: 'Mendyk' },
  { imie: 'Adam', nazwisko: 'Mertas' },
  { imie: 'Marcin', nazwisko: 'Michalski' },
  { imie: 'Magdalena', nazwisko: 'Micińska' },
  { imie: 'Urszula', nazwisko: 'Milewska' },
  { imie: 'Agnieszka', nazwisko: 'Morawska' },
  { imie: 'Karolina', nazwisko: 'Moszczyńska' },
  { imie: 'Adam', nazwisko: 'Moszyński' },
  { imie: 'Cezary', nazwisko: 'Młotek' },
  { imie: 'Anna', nazwisko: 'Mróz-Gazda' },
  { imie: 'Agnieszka', nazwisko: 'Nadstawna' },
  { imie: 'Kinga', nazwisko: 'Naglik' },
  { imie: 'Tomasz', nazwisko: 'Nahurny' },
  { imie: 'Andrzej', nazwisko: 'Nanowski' },
  { imie: 'Beata', nazwisko: 'Naróg' },
  { imie: 'Kamila', nazwisko: 'Niemczyk' },
  { imie: 'Maciej', nazwisko: 'Nosek' },
  { imie: 'Przemysław', nazwisko: 'Nowakowski-Węgrzynowski' },
  { imie: 'Katarzyna', nazwisko: 'Okońska' },
  { imie: 'Adam', nazwisko: 'Olczyk' },
  { imie: 'Kamil', nazwisko: 'Olech' },
  { imie: 'Agnieszka', nazwisko: 'Olejnik' },
  { imie: 'Agnieszka', nazwisko: 'Olszewska-Benewiat' },
  { imie: 'Monika', nazwisko: 'Ossowska' },
  { imie: 'Dobrochna', nazwisko: 'Owsicka' },
  { imie: 'Dawid', nazwisko: 'Paleczny' },
  { imie: 'Adam', nazwisko: 'Palowski' },
  { imie: 'Zbigniew', nazwisko: 'Paluszak' },
  { imie: 'Marcin', nazwisko: 'Parzyński' },
  { imie: 'Jakub', nazwisko: 'Paster' },
  { imie: 'Radosław', nazwisko: 'Pawełek' },
  { imie: 'Barbara', nazwisko: 'Pawełko-Czajka' },
  { imie: 'Agata', nazwisko: 'Pelc' },
  { imie: 'Mateusz', nazwisko: 'Perkowski' },
  { imie: 'Łukasz', nazwisko: 'Petelski' },
  { imie: 'Monika', nazwisko: 'Piątek' },
  { imie: 'Wojciech', nazwisko: 'Piątek' },
  { imie: 'Marcin', nazwisko: 'Piątek' },
  { imie: 'Tomasz', nazwisko: 'Pielichowski' },
  { imie: 'Łukasz', nazwisko: 'Pietruk' },
  { imie: 'Kamila', nazwisko: 'Piotrowska' },
  { imie: 'Magdalena', nazwisko: 'Podjacka' },
  { imie: 'Agnieszka', nazwisko: 'Polus' },
  { imie: 'Katarzyna', nazwisko: 'Poterucha' },
  { imie: 'Radosław', nazwisko: 'Potok' },
  { imie: 'Angelika', nazwisko: 'Poznańska' },
  { imie: 'n.', nazwisko: 'pr. Bartosz Smółka' },
  { imie: 'Tomasz', nazwisko: 'Pytkowski' },
  { imie: 'Olga', nazwisko: 'Raczyńska-Bućko' },
  { imie: 'Cezary', nazwisko: 'Radomski' },
  { imie: 'Karol', nazwisko: 'Rębisz' },
  { imie: 'Łukasz', nazwisko: 'Rogatka' },
  { imie: 'Kamil', nazwisko: 'Rogulski' },
  { imie: 'Michał', nazwisko: 'Rutkowski' },
  { imie: 'Martin', nazwisko: 'Rydygel' },
  { imie: 'Piotr', nazwisko: 'Sadowski' },
  { imie: 'Paulina', nazwisko: 'Salamon-Kinas' },
  { imie: 'Artur', nazwisko: 'Samek' },
  { imie: 'Mirosław', nazwisko: 'Sanek' },
  { imie: 'Maciej', nazwisko: 'Schab' },
  { imie: 'Olga', nazwisko: 'Schabowicz-Drzewińska' },
  { imie: 'WYSTEROWAŁ', nazwisko: 'SIĘ 1 DZIEŃ PRZED PIERWSZYM' },
  { imie: 'Tomasz', nazwisko: 'Siwak' },
  { imie: 'Katarzyna', nazwisko: 'Siwek' },
  { imie: 'Marcin', nazwisko: 'Skóra' },
  { imie: 'Monika', nazwisko: 'Skrodzka' },
  { imie: 'Marcin', nazwisko: 'Skuza' },
  { imie: 'Urszula', nazwisko: 'Śliwińska' },
  { imie: 'Joanna', nazwisko: 'Śliwińska' },
  { imie: 'Arkadiusz', nazwisko: 'Sobiech' },
  { imie: 'Maria', nazwisko: 'Sobieska' },
  { imie: 'Leszek', nazwisko: 'Sobieski' },
  { imie: 'Marcin', nazwisko: 'Sobota' },
  { imie: 'Dariusz', nazwisko: 'Słoniecki' },
  { imie: 'Natalia', nazwisko: 'Soroka-Tezcan' },
  { imie: 'Jadwiga', nazwisko: 'Sołtysek' },
  { imie: 'Justyna', nazwisko: 'Starek' },
  { imie: 'Marcin', nazwisko: 'Starzec' },
  { imie: 'Renata', nazwisko: 'Stefaniuk' },
  { imie: 'Roman', nazwisko: 'Stempel' },
  { imie: 'Michał', nazwisko: 'Stoliński' },
  { imie: 'Luiza', nazwisko: 'Stroińska' },
  { imie: 'Krzysztof', nazwisko: 'Stucke' },
  { imie: 'Dawid', nazwisko: 'Studencki' },
  { imie: 'Michał', nazwisko: 'Substyk' },
  { imie: 'Anna', nazwisko: 'Suder' },
  { imie: 'Agnieszkę', nazwisko: 'Sulich' },
  { imie: 'Gabriela', nazwisko: 'Suski-Borek' },
  { imie: 'płk', nazwisko: 'SW w st.spocz. Elżbieta Krakowska' },
  { imie: 'Iwona', nazwisko: 'Świąder' },
  { imie: 'Karolina', nazwisko: 'Swoboda-Bosak' },
  { imie: 'Aleksandra', nazwisko: 'Szabat-Ostęp' },
  { imie: 'Magdalena', nazwisko: 'Szabłowska' },
  { imie: 'Damian', nazwisko: 'Szczepaniak' },
  { imie: 'Wojciech', nazwisko: 'Szczotka' },
  { imie: 'Karolina', nazwisko: 'Szlom' },
  { imie: 'Małgorzata', nazwisko: 'Szreniawska' },
  { imie: 'Adam', nazwisko: 'Szubert' },
  { imie: 'Marta', nazwisko: 'Szulc-Ciesielska' },
  { imie: 'Izabela', nazwisko: 'Szwedziuk' },
  { imie: 'Robert', nazwisko: 'Szwejkowski' },
  { imie: 'Adrian', nazwisko: 'Szydlik' },
  { imie: 'Arkadiusz', nazwisko: 'Talik' },
  { imie: 'Natalia', nazwisko: 'Tatarczuk' },
  { imie: 'Alina', nazwisko: 'Terpińska' },
  { imie: 'test', nazwisko: 'test' },
  { imie: 'Anna', nazwisko: 'Tomala' },
  { imie: 'Krystian', nazwisko: 'Tuczyński' },
  { imie: 'Izabela', nazwisko: 'Tutur-Dudek' },
  { imie: 'Tomasz', nazwisko: 'Tworek' },
  { imie: 'Anna', nazwisko: 'Łukasik' },
  { imie: 'Andrzej', nazwisko: 'Łukaszewicz' },
  { imie: 'Michał', nazwisko: 'Urban' },
  { imie: 'Filip', nazwisko: 'Wasilewski' },
  { imie: 'Kamil', nazwisko: 'Wasilewski' },
  { imie: 'Adrian', nazwisko: 'Waszak' },
  { imie: 'Beata', nazwisko: 'Waszczyłko-Miłkowska' },
  { imie: 'Kamil', nazwisko: 'Wawrzeńczyk' },
  { imie: 'Michał', nazwisko: 'Wawrzonkowski' },
  { imie: 'Anna', nazwisko: 'Wdowiarz-Pelc' },
  { imie: 'Maciej', nazwisko: 'Wielogórski' },
  { imie: 'Renata', nazwisko: 'Wijata' },
  { imie: 'Adrianna', nazwisko: 'Winnicka-Siergiejuk' },
  { imie: 'Piotr', nazwisko: 'Wiśniewski' },
  { imie: 'Marcin', nazwisko: 'Wiśniewski' },
  { imie: 'Michał', nazwisko: 'Wójcik' },
  { imie: 'Rafał', nazwisko: 'Wojtaszek' },
  { imie: 'Anna', nazwisko: 'Wójtowicz-Dawid' },
  { imie: 'Iwona', nazwisko: 'Wołkiewicz' },
  { imie: 'Bartosz', nazwisko: 'Wolański' },
  { imie: 'Agnieszka', nazwisko: 'Wolszczak-Wiśniewska' },
  { imie: 'Agnieszka', nazwisko: 'Wołowiec' },
  { imie: 'Katarzyna', nazwisko: 'Woźniak' },
  { imie: 'Krzysztof', nazwisko: 'Woźnicki' },
  { imie: 'Karolina', nazwisko: 'Wróblewska' },
  { imie: 'Tomasz', nazwisko: 'Wypych' },
  { imie: 'Daria', nazwisko: 'Wyszyńska' },
  { imie: 'Michał', nazwisko: 'Zagłoba' },
  { imie: 'Kamil', nazwisko: 'Zagozdon' },
  { imie: 'Krzysztof', nazwisko: 'Zając' },
  { imie: 'Jakub', nazwisko: 'Żak' },
  { imie: 'Barbara', nazwisko: 'Zapała' },
  { imie: 'Agnieszka', nazwisko: 'Zaręba-Janowska' },
  { imie: 'Jacek', nazwisko: 'Zatoński' },
  { imie: 'Przemysław', nazwisko: 'Zdyb' },
  { imie: 'Tomasz', nazwisko: 'Żelichowski' },
  { imie: 'Monika', nazwisko: 'Zielińska' },
  { imie: 'Radosław', nazwisko: 'Ziemey' },
  { imie: 'Katarzyna', nazwisko: 'Zimolzak-Szydlik' },
  { imie: 'Damian', nazwisko: 'Żłobicki' },
  { imie: 'Aneta', nazwisko: 'Zuchowska-Prygiel' },
]

const mapaPolskichZnakow: Record<string, string> = {
  ą: 'a',
  ć: 'c',
  ę: 'e',
  ł: 'l',
  ń: 'n',
  ó: 'o',
  ś: 's',
  ź: 'z',
  ż: 'z',
}

function normalizujTekstTrenera(wartosc: string) {
  return wartosc
    .trim()
    .toLocaleLowerCase('pl')
    .split('')
    .map((znak) => mapaPolskichZnakow[znak] ?? znak)
    .join('')
}

function normalizujAliasTrenera(wartosc: string) {
  return normalizujTekstTrenera(wartosc).replace(/[^a-z0-9]/g, '')
}

function normalizujIdTrenera(wartosc: string) {
  return normalizujTekstTrenera(wartosc).replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
}

function pobierzPierwszyCzlonImienia(imie: string) {
  return imie.trim().split(/\s+/)[0] ?? ''
}

function pobierzPierwszyCzlonNazwiska(nazwisko: string) {
  return (nazwisko.trim().split(/\s+/)[0] ?? '').split('-')[0] ?? ''
}

export function utworzEmailTrenera(imie: string, nazwisko: string) {
  const inicjal = normalizujAliasTrenera(pobierzPierwszyCzlonImienia(imie)).slice(0, 1)
  const nazwiskoAlias = normalizujAliasTrenera(pobierzPierwszyCzlonNazwiska(nazwisko))

  return `${inicjal}.${nazwiskoAlias}@szkolenia-semper.pl`
}

export function utworzIdTrenera(imie: string, nazwisko: string) {
  return `trener-${normalizujIdTrenera(`${imie} ${nazwisko}`)}`
}

export const trenerzyKartotekiStartowi: TrenerKartoteki[] = trenerzyZCsv.map((trener) => ({
  id: utworzIdTrenera(trener.imie, trener.nazwisko),
  imieNazwisko: `${trener.imie} ${trener.nazwisko}`.trim(),
  telefon: '',
  email: utworzEmailTrenera(trener.imie, trener.nazwisko),
}))
