import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import test from 'node:test'

const wymagaj = createRequire(import.meta.url)
const { chromium } = wymagaj(process.env.POMAGIER_PLAYWRIGHT || 'playwright')
const adres = process.env.POMAGIER_ADRES || 'http://127.0.0.1:5173'

test('zakupy: podgląd, edycja, duplikacja, schowek, zapis i widoczność linków', { timeout: 120000 }, async () => {
  const przegladarka = await chromium.launch({ channel: 'chrome', headless: true })
  try {
    const kontekst = await przegladarka.newContext({ viewport: { width: 1440, height: 1000 } })
    const strona = await kontekst.newPage()
    const bledy = []
    strona.on('pageerror', (blad) => bledy.push(blad.message))
    await strona.goto(adres + '/pulpit')
    await strona.getByLabel('Aktywne konto').selectOption('administrator-kacper-madej')
    await strona.getByRole('button', { name: 'Zaloguj', exact: true }).click()
    await strona.locator('.pulpit-kafelek--zakupy').click()
    await strona.getByRole('button', { name: '+ Zgłoś zakup', exact: true }).click()
    await strona.getByLabel('Co jest potrzebne?').fill('Papier testowy')
    await strona.getByLabel('Ilość', { exact: true }).fill('20')
    await strona.getByLabel('Uwagi', { exact: true }).fill('Oferta do weryfikacji')
    await strona.getByLabel('Link do produktu 1', { exact: true }).fill('https://allegro.pl/oferta')
    await strona.getByRole('button', { name: 'Dodaj kolejny link', exact: true }).click()
    await strona.getByLabel('Link do produktu 2', { exact: true }).fill('https://sklep.pl/produkt')
    await strona.locator('.pulpit-formularz-zakupu').evaluate((formularz) => {
      const obraz = Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII='), (znak) => znak.charCodeAt(0))
      const schowek = new DataTransfer()
      schowek.items.add(new File([obraz], 'schowek.png', { type: 'image/png' }))
      formularz.dispatchEvent(new ClipboardEvent('paste', { clipboardData: schowek, bubbles: true, cancelable: true }))
    })
    await strona.getByRole('button', { name: 'Usuń załącznik schowek.png', exact: true }).waitFor()
    await strona.getByRole('button', { name: 'Zapisz', exact: true }).click()
    const kafelek = strona.locator('.pulpit-zapotrzebowanie').first()
    assert.equal(await kafelek.locator('a').count(), 0)
    assert.match(await kafelek.innerText(), /ZGŁOSZONE/)
    const wymiary = await kafelek.boundingBox()
    assert.ok(wymiary.height < 150, 'Kafelek powinien być kompaktowy')
    await kafelek.locator('.pulpit-zakup__podglad').click()
    let podglad = strona.getByRole('dialog', { name: 'Podgląd zapotrzebowania' })
    assert.equal(await podglad.locator('a[href="https://allegro.pl/oferta"]').count(), 1)
    assert.equal(await podglad.locator('img').count(), 1)
    await podglad.getByRole('button', { name: '✏️ Edytuj', exact: true }).click()
    assert.equal(await strona.getByLabel('Co jest potrzebne?').inputValue(), 'Papier testowy')
    await strona.getByLabel('Co jest potrzebne?').fill('Papier po edycji')
    await strona.evaluate(() => {
      window.zapisPrzedTestem = Storage.prototype.setItem
      Storage.prototype.setItem = function (klucz, wartosc) {
        if (klucz === 'ultimatePomagier.pulpit.v1') throw new DOMException('Brak miejsca', 'QuotaExceededError')
        return window.zapisPrzedTestem.call(this, klucz, wartosc)
      }
    })
    await strona.getByRole('button', { name: 'Zapisz', exact: true }).click()
    await strona.getByRole('alert').waitFor()
    assert.equal(await strona.getByLabel('Co jest potrzebne?').inputValue(), 'Papier po edycji')
    await strona.evaluate(() => { Storage.prototype.setItem = window.zapisPrzedTestem; delete window.zapisPrzedTestem })
    await strona.getByRole('button', { name: 'Zapisz', exact: true }).click()
    await kafelek.getByRole('button', { name: '📚 Duplikuj', exact: true }).click()
    await strona.getByRole('button', { name: 'Zapisz', exact: true }).click()
    assert.equal(await strona.locator('.pulpit-zapotrzebowanie').count(), 2)
    const zapisane = await strona.evaluate(() => JSON.parse(localStorage.getItem('ultimatePomagier.pulpit.v1')).zapotrzebowaniaZakupowe)
    assert.notEqual(zapisane[0].id, zapisane[1].id)
    assert.equal(zapisane[1].zalaczniki.length, 1)
    await strona.reload()
    await strona.locator('.pulpit-kafelek--zakupy').click()
    assert.equal(await strona.locator('.pulpit-zapotrzebowanie').count(), 2)
    await strona.locator('.pulpit-zapotrzebowanie').first().getByRole('button', { name: '✅ Kupione', exact: true }).click()
    assert.equal(await strona.locator('.pulpit-zapotrzebowanie').count(), 1)
    await strona.setViewportSize({ width: 575, height: 969 })
    const waskiKafelek = await strona.locator('.pulpit-zapotrzebowanie').boundingBox()
    assert.ok(waskiKafelek.height < 150)
    assert.ok(waskiKafelek.x + waskiKafelek.width <= 575)
    if (process.env.POMAGIER_ZRZUT) await strona.screenshot({ path: process.env.POMAGIER_ZRZUT })
    await strona.evaluate(() => localStorage.removeItem('ultimatePomagier.sesjaUzytkownika.v1'))
    await strona.reload()
    await strona.getByLabel('Aktywne konto').selectOption('pracownik-tomasz-czekaj')
    await strona.getByRole('button', { name: 'Zaloguj', exact: true }).click()
    await strona.locator('.pulpit-kafelek--zakupy').click()
    await strona.locator('.pulpit-zakup__podglad').click()
    podglad = strona.getByRole('dialog', { name: 'Podgląd zapotrzebowania' })
    assert.equal(await podglad.locator('a[href^="https:"]').count(), 0)
    await podglad.getByRole('button', { name: '✏️ Edytuj', exact: true }).click()
    assert.equal(await strona.getByLabel('Link do produktu 1', { exact: true }).count(), 0)
    await strona.getByLabel('Uwagi', { exact: true }).fill('Uwagi pracownika')
    await strona.getByRole('button', { name: 'Zapisz', exact: true }).click()
    const poEdycji = await strona.evaluate(() => JSON.parse(localStorage.getItem('ultimatePomagier.pulpit.v1')).zapotrzebowaniaZakupowe)
    assert.equal(poEdycji[1].linkiProduktow.length, 2)
    await strona.getByRole('button', { name: '❌ Usuń', exact: true }).click()
    assert.equal(await strona.locator('.pulpit-zapotrzebowanie').count(), 0)
    assert.deepEqual(bledy, [])
  } finally { await przegladarka.close() }
})
