export type WidokNawigacji =
  | 'pulpit'
  | 'szkolenia-zamkniete'
  | 'generator-szczegolow'
  | 'zamkniete_szczegoly_organizacyjne_nowe'
  | 'szkolenia-otwarte'
  | 'dokumenty'
  | 'replikator_dokumentow'
  | 'listy-obecnosci'
  | 'ankiety'
  | 'dyplomy'
  | 'programy_szkolen'
  | 'kartoteki'
  | 'kartoteki_trenerzy'
  | 'kartoteki_klienci'
  | 'kartoteki_lokalizacje'
  | 'ustawienia'
